version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf

  prometheus:
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus:latest
    expose:
      - "9090"
    volumes:
      - /etc/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana-oss:latest
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana

  speedtest:
    container_name: speedtest
    restart: unless-stopped
    image: normandabald/speedtest:latest
    expose:
      - "8000"
