{
 "title": "Home Metrics",
 "time": { "from": "2022-10-29T20:13:01.381Z", "to": "2022-10-29T20:43:01.381Z" },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed / 1000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "download_speed", "legendFormat": "__auto" },
    { "expr": "upload_speed", "legendFormat": "__auto" }
   ]
  },
  { "title": "Lloyd's PC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((16 * 1073741824) - windows_os_physical_memory_free_bytes)/(16 * 1073741824))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Remaining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"C:\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "windows_logical_disk_free_bytes{volume=\"D:\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}