---

  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
      state: present

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: install docker 
    package:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes
      state: latest

  - name: add user permissions
    shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

  - name: Reset ssh connection for changes to take effect
    meta: "reset_connection"

  # Installs Docker SDK
  # --
  # 
  - name: install python package manager
    apt:
      name: python3-pip

  - name: install python sdk
    become: true
    pip:
      name:
        - docker
        - docker-compose